package miniJava.SyntacticAnalyzer;

public enum TokenType {
    CLASS, VOID, PUBLIC, PRIVATE, STATIC, INT, BOOLEAN, THIS, TRUE, FALSE, NEW, ID, RETURN, IF, ELSE, WHILE, OPEN_P,
    CLOSED_P, OPEN_BRACE, CLOSED_BRACE, COMMA, SEMICOLON, OPEN_BRACKET, CLOSED_BRACKET, OPERATOR,
    INT_LITERAL, PERIOD, EOF, EQUAL, ERROR;
}
